services:
  web:
    build: .
    container_name: inventory_web
    restart: always
    ports:
      - "80:8092"
    volumes:
      - .:/app
      - static_volume:/app/build/staticfiles
      - media_volume:/app/build/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - Abhaydan

  db:
    image: postgres:15
    container_name: inventory_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - Inventory 

networks:
  Inventory:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
