services:
  web:
    build: .
    container_name: inventory_web
    restart: always
    ports:
      - "80:8092"
    volumes:
      - .:/app
      - static_volume:/app/build/staticfiles
      - media_volume:/app/build/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  static_volume:
  media_volume:
  postgres_data:
