import Login from "./Login/Login";
import Signup from "./Signup/Signup";
import Dashboard from "./Dashboard/Dashboard";
import PrivateRoute from "./PrivateRoute";
import Pending from "./Inventories/Pending";
import Approved from "./Inventories/Approved";
import Approved_Graph from "./Analytics/Approved_Graph";
import Pending_Graph from "./Analytics/Pending_graph";
import Add from "./Add/Add";
export { Login, Signup, PrivateRoute, Pending, Approved ,Dashboard, Add, Approved_Graph, Pending_Graph };
