# Generated by Django 4.2 on 2024-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="inventory",
            fields=[
                (
                    "product_id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("product_name", models.CharField(max_length=254)),
                ("vendor", models.CharField(max_length=254)),
                ("mrp", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("batch_no", models.CharField(max_length=254)),
                ("batch_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Approved", "Approved")],
                        default="Pending",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
